#!/bin/sh -e
poetry run black forge --exclude migrations "$@"
poetry run isort forge --settings-file forge/forge_isort.cfg --skip template "$@"

poetry run black tests "$@"
poetry run isort tests --profile black "$@"

poetry run black quickstart.py "$@"
poetry run isort quickstart.py --profile black "$@"
