#!/bin/sh -e
# Set up a forge-quickstart-test directory next to this repo
cd ..
rm -rf forge-quickstart-test
cat forge/quickstart.py | python3 - forge-quickstart-test --source ./starter-template
cd forge-quickstart-test
rm -rf .venv
export POETRY_VIRTUALENVS_IN_PROJECT=true
poetry add ../forge
poetry update
